# Generated by Django 5.1.3 on 2024-11-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concierto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=100)),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('tema', models.CharField(max_length=200)),
                ('orador', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
